package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "resotrekk")
public class Administrateur implements java.io.Serializable {

	private Integer idAdmin;
	private String emailAdmin;
	private String motDePasse;
	private String nomAdmin;
	private String prenomAdmin;
	private boolean enabled;
	private String photo;

	public Administrateur() {
	}

	public Administrateur(String emailAdmin, String motDePasse, boolean enabled) {
		this.emailAdmin = emailAdmin;
		this.motDePasse = motDePasse;
		this.enabled = enabled;
	}

	public Administrateur(String emailAdmin, String motDePasse,
			String nomAdmin, String prenomAdmin, boolean enabled, String photo, String autorite) {
		this.emailAdmin = emailAdmin;
		this.motDePasse = motDePasse;
		this.nomAdmin = nomAdmin;
		this.prenomAdmin = prenomAdmin;
		this.enabled = enabled;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAdmin", unique = true, nullable = false)
	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "email_admin", nullable = false, length = 60)
	public String getEmailAdmin() {
		return this.emailAdmin;
	}

	public void setEmailAdmin(String emailAdmin) {
		this.emailAdmin = emailAdmin;
	}

	@Column(name = "mot_de_passe", nullable = false, length = 45)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "nom_admin", length = 45)
	public String getNomAdmin() {
		return this.nomAdmin;
	}

	public void setNomAdmin(String nomAdmin) {
		this.nomAdmin = nomAdmin;
	}

	@Column(name = "prenom_admin", length = 45)
	public String getPrenomAdmin() {
		return this.prenomAdmin;
	}

	public void setPrenomAdmin(String prenomAdmin) {
		this.prenomAdmin = prenomAdmin;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "photo", length = 100)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}


	
}
