package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Candidatures generated by hbm2java
 */
@Entity
@Table(name = "candidatures", catalog = "resotrekk")
public class Candidatures implements java.io.Serializable {

	private Integer idcandidatures;
	private Candidat candidat;
	private Offre offre;

	public Candidatures() {
	}

	public Candidatures(Candidat candidat, Offre offre) {
		this.candidat = candidat;
		this.offre = offre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcandidatures", unique = true, nullable = false)
	public Integer getIdcandidatures() {
		return this.idcandidatures;
	}

	public void setIdcandidatures(Integer idcandidatures) {
		this.idcandidatures = idcandidatures;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "candidat", nullable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "offre", nullable = false)
	public Offre getOffre() {
		return this.offre;
	}

	public void setOffre(Offre offre) {
		this.offre = offre;
	}

}
