package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import  javax.persistence.CascadeType;

/**
 * Candidat generated by hbm2java
 */
@Entity
@Table(name = "candidat", catalog = "resotrekk")
public class Candidat implements java.io.Serializable {

	private Integer idCandidat;
	private String nomCandidat;
	private String prenomCandidat;
	private String emailCandidat;
	private String motDePasseCandidat;
	private String telCandidat;
	private String adresseCandidat;
	private String villeCandidat;
	private String codePostalCandidat;
	private boolean enabled;
	private String societeCandidat;
	private String infoSupplementaires;
	private String cvCandidat;
	private String photoprofil;
	private Set<LangueCandidat> langueCandidats = new HashSet<LangueCandidat>(0);
	private Set<Candidatures> candidatureses = new HashSet<Candidatures>(0);
	private Set<ExperienceCandidat> experienceCandidats = new HashSet<ExperienceCandidat>(
			0);
	private Set<RoleCandidat> roleCandidats = new HashSet<RoleCandidat>(0);
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
	private Set<CompetencesCandidat> competencesCandidats = new HashSet<CompetencesCandidat>(
			0);
	private Set<Invitation> invitations = new HashSet<Invitation>(0);

	public Candidat() {
	}

	public Candidat(boolean enabled, String cvCandidat, String photoprofil) {
		this.enabled = enabled;
		this.cvCandidat = cvCandidat;
		this.photoprofil = photoprofil;
	}

	public Candidat(String nomCandidat, String prenomCandidat,
			String emailCandidat, String motDePasseCandidat,
			String telCandidat, String adresseCandidat, String villeCandidat,
			String codePostalCandidat, boolean enabled, String societeCandidat,
			String infoSupplementaires, String cvCandidat, String photoprofil,
			Set<LangueCandidat> langueCandidats,
			Set<Candidatures> candidatureses,
			Set<ExperienceCandidat> experienceCandidats,
			Set<RoleCandidat> roleCandidats, Set<Feedback> feedbacks,
			Set<CompetencesCandidat> competencesCandidats,
			Set<Invitation> invitations) {
		this.nomCandidat = nomCandidat;
		this.prenomCandidat = prenomCandidat;
		this.emailCandidat = emailCandidat;
		this.motDePasseCandidat = motDePasseCandidat;
		this.telCandidat = telCandidat;
		this.adresseCandidat = adresseCandidat;
		this.villeCandidat = villeCandidat;
		this.codePostalCandidat = codePostalCandidat;
		this.enabled = enabled;
		this.societeCandidat = societeCandidat;
		this.infoSupplementaires = infoSupplementaires;
		this.cvCandidat = cvCandidat;
		this.photoprofil = photoprofil;
		this.langueCandidats = langueCandidats;
		this.candidatureses = candidatureses;
		this.experienceCandidats = experienceCandidats;
		this.roleCandidats = roleCandidats;
		this.feedbacks = feedbacks;
		this.competencesCandidats = competencesCandidats;
		this.invitations = invitations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_candidat", unique = true, nullable = false)
	public Integer getIdCandidat() {
		return this.idCandidat;
	}

	public void setIdCandidat(Integer idCandidat) {
		this.idCandidat = idCandidat;
	}

	@Column(name = "nom_candidat", length = 30)
	public String getNomCandidat() {
		return this.nomCandidat;
	}

	public void setNomCandidat(String nomCandidat) {
		this.nomCandidat = nomCandidat;
	}

	@Column(name = "prenom_candidat", length = 30)
	public String getPrenomCandidat() {
		return this.prenomCandidat;
	}

	public void setPrenomCandidat(String prenomCandidat) {
		this.prenomCandidat = prenomCandidat;
	}

	@Column(name = "email_candidat", length = 60)
	public String getEmailCandidat() {
		return this.emailCandidat;
	}

	public void setEmailCandidat(String emailCandidat) {
		this.emailCandidat = emailCandidat;
	}

	@Column(name = "mot_de_passe_candidat", length = 50)
	public String getMotDePasseCandidat() {
		return this.motDePasseCandidat;
	}

	public void setMotDePasseCandidat(String motDePasseCandidat) {
		this.motDePasseCandidat = motDePasseCandidat;
	}

	@Column(name = "tel_candidat", length = 15)
	public String getTelCandidat() {
		return this.telCandidat;
	}

	public void setTelCandidat(String telCandidat) {
		this.telCandidat = telCandidat;
	}

	@Column(name = "adresse_candidat", length = 70)
	public String getAdresseCandidat() {
		return this.adresseCandidat;
	}

	public void setAdresseCandidat(String adresseCandidat) {
		this.adresseCandidat = adresseCandidat;
	}

	@Column(name = "Ville_candidat", length = 45)
	public String getVilleCandidat() {
		return this.villeCandidat;
	}

	public void setVilleCandidat(String villeCandidat) {
		this.villeCandidat = villeCandidat;
	}

	@Column(name = "code_postal_candidat", length = 8)
	public String getCodePostalCandidat() {
		return this.codePostalCandidat;
	}

	public void setCodePostalCandidat(String codePostalCandidat) {
		this.codePostalCandidat = codePostalCandidat;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "societe_candidat", length = 50)
	public String getSocieteCandidat() {
		return this.societeCandidat;
	}

	public void setSocieteCandidat(String societeCandidat) {
		this.societeCandidat = societeCandidat;
	}

	@Column(name = "info_supplementaires", length = 65535)
	public String getInfoSupplementaires() {
		return this.infoSupplementaires;
	}

	public void setInfoSupplementaires(String infoSupplementaires) {
		this.infoSupplementaires = infoSupplementaires;
	}

	@Column(name = "cv_candidat", nullable = false, length = 45)
	public String getCvCandidat() {
		return this.cvCandidat;
	}

	public void setCvCandidat(String cvCandidat) {
		this.cvCandidat = cvCandidat;
	}

	@Column(name = "photoprofil", nullable = false, length = 150)
	public String getPhotoprofil() {
		return this.photoprofil;
	}

	public void setPhotoprofil(String photoprofil) {
		this.photoprofil = photoprofil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<LangueCandidat> getLangueCandidats() {
		return this.langueCandidats;
	}

	public void setLangueCandidats(Set<LangueCandidat> langueCandidats) {
		this.langueCandidats = langueCandidats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<Candidatures> getCandidatureses() {
		return this.candidatureses;
	}

	public void setCandidatureses(Set<Candidatures> candidatureses) {
		this.candidatureses = candidatureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<ExperienceCandidat> getExperienceCandidats() {
		return this.experienceCandidats;
	}

	public void setExperienceCandidats(
			Set<ExperienceCandidat> experienceCandidats) {
		this.experienceCandidats = experienceCandidats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<RoleCandidat> getRoleCandidats() {
		return this.roleCandidats;
	}

	public void setRoleCandidats(Set<RoleCandidat> roleCandidats) {
		this.roleCandidats = roleCandidats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<CompetencesCandidat> getCompetencesCandidats() {
		return this.competencesCandidats;
	}

	public void setCompetencesCandidats(
			Set<CompetencesCandidat> competencesCandidats) {
		this.competencesCandidats = competencesCandidats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat", cascade={CascadeType.REMOVE})
	public Set<Invitation> getInvitations() {
		return this.invitations;
	}

	public void setInvitations(Set<Invitation> invitations) {
		this.invitations = invitations;
	}

}
