package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Competences generated by hbm2java
 */
@Entity
@Table(name = "competences", catalog = "resotrekk")
public class Competences implements java.io.Serializable {

	private Integer idcompetences;
	private String libelleCompetence;
	private Set<CompetencesCandidat> competencesCandidats = new HashSet<CompetencesCandidat>(
			0);

	public Competences() {
	}

	public Competences(String libelleCompetence) {
		this.libelleCompetence = libelleCompetence;
	}

	public Competences(String libelleCompetence,
			Set<CompetencesCandidat> competencesCandidats) {
		this.libelleCompetence = libelleCompetence;
		this.competencesCandidats = competencesCandidats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcompetences", unique = true, nullable = false)
	public Integer getIdcompetences() {
		return this.idcompetences;
	}

	public void setIdcompetences(Integer idcompetences) {
		this.idcompetences = idcompetences;
	}

	@Column(name = "libelle_competence", nullable = false, length = 80)
	public String getLibelleCompetence() {
		return this.libelleCompetence;
	}

	public void setLibelleCompetence(String libelleCompetence) {
		this.libelleCompetence = libelleCompetence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competences", cascade={CascadeType.REMOVE})
	public Set<CompetencesCandidat> getCompetencesCandidats() {
		return this.competencesCandidats;
	}

	public void setCompetencesCandidats(
			Set<CompetencesCandidat> competencesCandidats) {
		this.competencesCandidats = competencesCandidats;
	}

}
