package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompetencesCandidat generated by hbm2java
 */
@Entity
@Table(name = "competences_candidat", catalog = "resotrekk")
public class CompetencesCandidat implements java.io.Serializable {

	private Integer idcompetenceCandidat;
	private Competences competences;
	private Candidat candidat;

	public CompetencesCandidat() {
	}

	public CompetencesCandidat(Competences competences, Candidat candidat) {
		this.competences = competences;
		this.candidat = candidat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcompetence_candidat", unique = true, nullable = false)
	public Integer getIdcompetenceCandidat() {
		return this.idcompetenceCandidat;
	}

	public void setIdcompetenceCandidat(Integer idcompetenceCandidat) {
		this.idcompetenceCandidat = idcompetenceCandidat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "competence", nullable = false)
	public Competences getCompetences() {
		return this.competences;
	}

	public void setCompetences(Competences competences) {
		this.competences = competences;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidat", nullable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

}
