package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExperienceCandidat generated by hbm2java
 */
@Entity
@Table(name = "experience_candidat", catalog = "resotrekk")
public class ExperienceCandidat implements java.io.Serializable {

	private Integer idexperience;
	private Candidat candidat;
	private String societe;
	private String poste;
	private String descriptionPoste;

	public ExperienceCandidat() {
	}

	public ExperienceCandidat(Candidat candidat, String societe) {
		this.candidat = candidat;
		this.societe = societe;
	}

	public ExperienceCandidat(Candidat candidat, String societe, String poste,
			String descriptionPoste) {
		this.candidat = candidat;
		this.societe = societe;
		this.poste = poste;
		this.descriptionPoste = descriptionPoste;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idexperience", unique = true, nullable = false)
	public Integer getIdexperience() {
		return this.idexperience;
	}

	public void setIdexperience(Integer idexperience) {
		this.idexperience = idexperience;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidat", nullable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Column(name = "societe", nullable = false, length = 60)
	public String getSociete() {
		return this.societe;
	}

	public void setSociete(String societe) {
		this.societe = societe;
	}

	@Column(name = "poste", length = 70)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Column(name = "description_poste", length = 65535)
	public String getDescriptionPoste() {
		return this.descriptionPoste;
	}

	public void setDescriptionPoste(String descriptionPoste) {
		this.descriptionPoste = descriptionPoste;
	}

}
