package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "resotrekk")
public class Feedback implements java.io.Serializable {

	private Integer idfeedack;
	private Candidat candidat;
	private String commentFeedback;

	public Feedback() {
	}

	public Feedback(Candidat candidat, String commentFeedback) {
		this.candidat = candidat;
		this.commentFeedback = commentFeedback;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idfeedack", unique = true, nullable = false)
	public Integer getIdfeedack() {
		return this.idfeedack;
	}

	public void setIdfeedack(Integer idfeedack) {
		this.idfeedack = idfeedack;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "candidat", nullable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Column(name = "comment_feedback", nullable = false, length = 65535)
	public String getCommentFeedback() {
		return this.commentFeedback;
	}

	public void setCommentFeedback(String commentFeedback) {
		this.commentFeedback = commentFeedback;
	}

}
