package com.resotrekk.model;

// Generated 9 juil. 2015 11:31:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "historique", catalog = "resotrekk")
public class Historique implements java.io.Serializable {

	private Integer idhistorique;
	private String description;

	public Historique() {
	}

	public Historique(Administrateur administrateur, String description) {
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idhistorique", unique = true, nullable = false)
	public Integer getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(Integer idhistorique) {
		this.idhistorique = idhistorique;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
