package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offre generated by hbm2java
 */
@Entity
@Table(name = "offre", catalog = "resotrekk")
public class Offre implements java.io.Serializable {

	private Integer idoffre;
	private String titreOffre;
	private String posteOffre;
	private String descriptionMoinOffre;
	private String dateOffre;
	private int nombrePosteOffre;
	private String villeOffre;
	private String resumeOffre;
	private String responsabilitesOffre;
	private String offresOffre;
	private Set<Candidatures> candidatureses = new HashSet<Candidatures>(0);

	public Offre() {
	}

	public Offre(String titreOffre, String posteOffre,
			String descriptionMoinOffre, String dateOffre,
			int nombrePosteOffre, String villeOffre, String resumeOffre,
			String responsabilitesOffre, String offresOffre) {
		this.titreOffre = titreOffre;
		this.posteOffre = posteOffre;
		this.descriptionMoinOffre = descriptionMoinOffre;
		this.dateOffre = dateOffre;
		this.nombrePosteOffre = nombrePosteOffre;
		this.villeOffre = villeOffre;
		this.resumeOffre = resumeOffre;
		this.responsabilitesOffre = responsabilitesOffre;
		this.offresOffre = offresOffre;
	}

	public Offre(String titreOffre, String posteOffre,
			String descriptionMoinOffre, String dateOffre,
			int nombrePosteOffre, String villeOffre, String resumeOffre,
			String responsabilitesOffre, String offresOffre,
			Set<Candidatures> candidatureses) {
		this.titreOffre = titreOffre;
		this.posteOffre = posteOffre;
		this.descriptionMoinOffre = descriptionMoinOffre;
		this.dateOffre = dateOffre;
		this.nombrePosteOffre = nombrePosteOffre;
		this.villeOffre = villeOffre;
		this.resumeOffre = resumeOffre;
		this.responsabilitesOffre = responsabilitesOffre;
		this.offresOffre = offresOffre;
		this.candidatureses = candidatureses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idoffre", unique = true, nullable = false)
	public Integer getIdoffre() {
		return this.idoffre;
	}

	public void setIdoffre(Integer idoffre) {
		this.idoffre = idoffre;
	}

	@Column(name = "titre_offre", nullable = false, length = 100)
	public String getTitreOffre() {
		return this.titreOffre;
	}

	public void setTitreOffre(String titreOffre) {
		this.titreOffre = titreOffre;
	}

	@Column(name = "poste_offre", nullable = false, length = 100)
	public String getPosteOffre() {
		return this.posteOffre;
	}

	public void setPosteOffre(String posteOffre) {
		this.posteOffre = posteOffre;
	}

	@Column(name = "description_moin_offre", nullable = false, length = 400)
	public String getDescriptionMoinOffre() {
		return this.descriptionMoinOffre;
	}

	public void setDescriptionMoinOffre(String descriptionMoinOffre) {
		this.descriptionMoinOffre = descriptionMoinOffre;
	}

	@Column(name = "date_offre", nullable = false, length = 45)
	public String getDateOffre() {
		return this.dateOffre;
	}

	public void setDateOffre(String dateOffre) {
		this.dateOffre = dateOffre;
	}

	@Column(name = "nombre_poste_offre", nullable = false)
	public int getNombrePosteOffre() {
		return this.nombrePosteOffre;
	}

	public void setNombrePosteOffre(int nombrePosteOffre) {
		this.nombrePosteOffre = nombrePosteOffre;
	}

	@Column(name = "ville_offre", nullable = false, length = 45)
	public String getVilleOffre() {
		return this.villeOffre;
	}

	public void setVilleOffre(String villeOffre) {
		this.villeOffre = villeOffre;
	}

	@Column(name = "resume_offre", nullable = false, length = 65535)
	public String getResumeOffre() {
		return this.resumeOffre;
	}

	public void setResumeOffre(String resumeOffre) {
		this.resumeOffre = resumeOffre;
	}

	@Column(name = "responsabilites_offre", nullable = false, length = 65535)
	public String getResponsabilitesOffre() {
		return this.responsabilitesOffre;
	}

	public void setResponsabilitesOffre(String responsabilitesOffre) {
		this.responsabilitesOffre = responsabilitesOffre;
	}

	@Column(name = "offres_offre", nullable = false, length = 65535)
	public String getOffresOffre() {
		return this.offresOffre;
	}

	public void setOffresOffre(String offresOffre) {
		this.offresOffre = offresOffre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offre", cascade={CascadeType.REMOVE})
	public Set<Candidatures> getCandidatureses() {
		return this.candidatureses;
	}

	public void setCandidatureses(Set<Candidatures> candidatureses) {
		this.candidatureses = candidatureses;
	}

}
