package com.resotrekk.model;

// Generated 18 juin 2015 09:54:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleCandidat generated by hbm2java
 */
@Entity
@Table(name = "role_candidat", catalog = "resotrekk")
public class RoleCandidat implements java.io.Serializable {

	private Integer idroleCandidat;
	private Candidat candidat;
	private String autorite;

	public RoleCandidat() {
	}

	public RoleCandidat(Candidat candidat, String autorite) {
		this.candidat = candidat;
		this.autorite = autorite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrole_candidat", unique = true, nullable = false)
	public Integer getIdroleCandidat() {
		return this.idroleCandidat;
	}

	public void setIdroleCandidat(Integer idroleCandidat) {
		this.idroleCandidat = idroleCandidat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidat", nullable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Column(name = "autorite", nullable = false, length = 45)
	public String getAutorite() {
		return this.autorite;
	}

	public void setAutorite(String autorite) {
		this.autorite = autorite;
	}

}
